force-app/main/default/objects/KYC_Validator_Postgress_cred__mdt/KYC_Validator_Postgress_cred__mdt.object-meta.xml
<CustomObject>
    <label>KYC Validator Postgress cred</label>
    <pluralLabel>KYC Validator Postgress creds</pluralLabel>
</CustomObject>

force-app/main/default/objects/KYC_Validator_Postgress_cred__mdt/fields/Creds_URL__c.field-meta.xml
<CustomField>
    <fullName>Creds_URL__c</fullName>
    <label>Creds URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/KYCValidatorFunctionCall.cls
/**
 * @description       : 
 * @author            : Ajitesh
 * @group             : 
 * @last modified on  : 12-04-2022
 * @last modified by  : Ajitesh
**/
public with sharing class KYCValidatorFunctionCall {

    public class FlowInputVariable{
        @InvocableVariable
        public String panCardNo;
        @InvocableVariable
        public String aadhaarNo;
    }

    public class PostgressCreds{
        public String databaseUri;
    }

    public class SalesforcefunctionInput{
        public String panCardNo;
        public String aadhaarNo;
        public PostgressCreds creds;
    }

    public class SalesforceFunctionOutputVariable{
        @InvocableVariable public Boolean isAadhaarValidated;
        @InvocableVariable public Boolean isPanValidated;
    }

    @InvocableMethod(label = 'OCR Helper Function Call')
    public static void KYCValidatorFunctionCall(List<FlowInputVariable> flowInput) {
        KYC_Validator_Postgress_cred__mdt kycValidatorRec = [SELECT Creds_URL__c FROM KYC_Validator_Postgress_cred__mdt LIMIT 1];

        PostgressCreds creds = new PostgressCreds();
        creds.databaseUri = kycValidatorRec.Creds_URL__c;
        
        SalesforcefunctionInput funcinputs = new SalesforcefunctionInput();
        funcinputs.aadhaarNo = flowInput[0].aadhaarNo;
        funcinputs.panCardNo = flowInput[0].panCardNo;
        funcinputs.creds = creds;



    }
}